---
- hosts: "{{ hostlist }}"
  become: true
  become_user: root
  tasks:
    - name: 'create ~/.aws directory'
      file:
        path: '/home/deploy/.aws'
        state: directory
        mode: 0755
        owner: www-data
        group: www-data
    - name: 'copy aws credentials to ~/.aws/credentials on server'
      template:
        src: '{{ playbook_dir }}/templates/aws-credentials.j2'
        dest: /home/deploy/.aws/credentials
        owner: www-data
        group: www-data
        mode: 0644
