---
- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.28
- name: dns
  src: oefenweb.dns
  version: v1.1.26
- name: ntp
  src: oefenweb.ntp
  version: v1.1.28
- name: fail2ban
  src: oefenweb.fail2ban
  version: v3.3.13
- name: timezone
  src: oefenweb.timezone
  version: v1.0.42
- name: unattended-upgrades
  src: jnv.unattended-upgrades
  version: v1.8.0
- name: nodejs
  src: oefenweb.nodejs
  version: v6.0.3
- name: yarn
  src: oefenweb.yarn
  version: v1.0.42
- name: pip
  src: oefenweb.pip
  version: v2.1.1
- name: sysctl
  src: oefenweb.sysctl
  version: v1.0.36
- name: redis
  src: oefenweb.redis
  version: v3.0.29
- name: mongo
  src: https://github.com/niftylettuce/ansible-role-mongodb.git
  version: master
  # src: undergreen.mongodb
  # version: v2.6.1
- name: ssh-keys
  src: oefenweb.ssh_keys
  version: v2.1.4
- name: fqdn
  src: holms.fqdn
  version: '1.1'
- name: mongo-shell
  src: enix.mongodb
  version: '1.1.1'
